// MULTITALENTED product catalogue — single source of truth.
// Prices and variants below are transcribed from the catalogue images supplied by the owner.
// Apple/iPhone source image contains variants but no prices, so those prices are null.
// Do not invent prices; update null values only when a verified business price is available.

const products = [
    {
        "id": "apple-iphone-7-32gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 7",
        "variant": "32GB",
        "ram": null,
        "storage": "32GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-7-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 7",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-7-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 7",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-7-plus-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 7 Plus",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-7-plus-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 7 Plus",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-7-fe-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 7 FE",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-7-fe-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 7 FE",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-8-64gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 8",
        "variant": "64GB",
        "ram": null,
        "storage": "64GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-8-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 8",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-8-plus-64gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 8 Plus",
        "variant": "64GB",
        "ram": null,
        "storage": "64GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-8-plus-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 8 Plus",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-x-64gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone X",
        "variant": "64GB",
        "ram": null,
        "storage": "64GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-x-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone X",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-xr-64gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone XR",
        "variant": "64GB",
        "ram": null,
        "storage": "64GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-xr-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone XR",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-xs-64gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone XS",
        "variant": "64GB",
        "ram": null,
        "storage": "64GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-xs-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone XS",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-11-64gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 11",
        "variant": "64GB",
        "ram": null,
        "storage": "64GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-11-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 11",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-11-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 11",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-12-64gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 12",
        "variant": "64GB",
        "ram": null,
        "storage": "64GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-12-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 12",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-12-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 12",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-12-pro-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 12 Pro",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-12-pro-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 12 Pro",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-13-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 13",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-13-128gb-duplicate-2",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 13",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-13-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 13",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-13-512gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 13",
        "variant": "512GB",
        "ram": null,
        "storage": "512GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-13-pro-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 13 Pro",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-13-pro-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 13 Pro",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-13-pro-512gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 13 Pro",
        "variant": "512GB",
        "ram": null,
        "storage": "512GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-14-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 14",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-14-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 14",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-14-plus-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 14 Plus",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-14-plus-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 14 Plus",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-14-pro-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 14 Pro",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-14-pro-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 14 Pro",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-14-pro-max-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 14 Pro Max",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": true
    },
    {
        "id": "apple-iphone-14-pro-max-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 14 Pro Max",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": true
    },
    {
        "id": "apple-iphone-15-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 15",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-15-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 15",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-15-plus-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 15 Plus",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-15-plus-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 15 Plus",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": false
    },
    {
        "id": "apple-iphone-15-pro-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 15 Pro",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": true
    },
    {
        "id": "apple-iphone-15-pro-max-128gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 15 Pro Max",
        "variant": "128GB",
        "ram": null,
        "storage": "128GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": true
    },
    {
        "id": "apple-iphone-15-pro-max-256gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 15 Pro Max",
        "variant": "256GB",
        "ram": null,
        "storage": "256GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": true
    },
    {
        "id": "apple-iphone-15-pro-max-512gb",
        "brand": "Apple",
        "category": "Smartphones",
        "model": "iPhone 15 Pro Max",
        "variant": "512GB",
        "ram": null,
        "storage": "512GB",
        "price": null,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Price not supplied",
        "description": "",
        "featured": true
    },
    {
        "id": "tecno-tecno-spark-30-4-128gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Spark 30",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 139800,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-spark-30c-4-128gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Spark 30C",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 126450,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-spark-30-pro-8-256gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Spark 30 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 159350,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-camon-30-6-128gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Camon 30",
        "variant": "6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 209780,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-camon-30-pro-8-256gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Camon 30 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 258970,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-camon-30-premier-12-512gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Camon 30 Premier",
        "variant": "12+512GB",
        "ram": "12GB",
        "storage": "512GB",
        "price": 339760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-pova-6-8-128gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Pova 6",
        "variant": "8+128GB",
        "ram": "8GB",
        "storage": "128GB",
        "price": 189420,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-pova-6-pro-12-256gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Pova 6 Pro",
        "variant": "12+256GB",
        "ram": "12GB",
        "storage": "256GB",
        "price": 241680,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-pova-5-8-128gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Pova 5",
        "variant": "8+128GB",
        "ram": "8GB",
        "storage": "128GB",
        "price": 163950,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-pova-5-pro-8-256gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Pova 5 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 207350,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-phantom-v-fold-12-512gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Phantom V Fold",
        "variant": "12+512GB",
        "ram": "12GB",
        "storage": "512GB",
        "price": 778760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": true
    },
    {
        "id": "tecno-tecno-phantom-v-flip-8-256gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Phantom V Flip",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 606720,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": true
    },
    {
        "id": "tecno-tecno-phantom-x2-8-256gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Phantom X2",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 490350,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-spark-go-2024-3-64gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Spark Go 2024",
        "variant": "3+64GB",
        "ram": "3GB",
        "storage": "64GB",
        "price": 95420,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-spark-20-8-128gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Spark 20",
        "variant": "8+128GB",
        "ram": "8GB",
        "storage": "128GB",
        "price": 144780,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-spark-20-pro-8-256gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Spark 20 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 175680,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-pop-9-4-64gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Pop 9",
        "variant": "4+64GB",
        "ram": "4GB",
        "storage": "64GB",
        "price": 86930,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-pop-8-3-64gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Pop 8",
        "variant": "3+64GB",
        "ram": "3GB",
        "storage": "64GB",
        "price": 74520,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-camon-20-8-256gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Camon 20",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 217460,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-camon-20-pro-8-256gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Camon 20 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 262320,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-phantom-x-8-256gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Phantom X",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 384760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-spark-10-8-128gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Spark 10",
        "variant": "8+128GB",
        "ram": "8GB",
        "storage": "128GB",
        "price": 119560,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-spark-10-pro-8-256gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Spark 10 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 146870,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-pova-neo-4-128gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Pova Neo",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 112450,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-pop-7-3-64gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Pop 7",
        "variant": "3+64GB",
        "ram": "3GB",
        "storage": "64GB",
        "price": 69780,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-spark-9-4-128gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Spark 9",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 104670,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "tecno-tecno-camon-19-6-128gb",
        "brand": "Tecno",
        "category": "Smartphones",
        "model": "Camon 19",
        "variant": "6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 167230,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-note-50-8-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Note 50",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 180450,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-note-50-pro-12-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Note 50 Pro",
        "variant": "12+256GB",
        "ram": "12GB",
        "storage": "256GB",
        "price": 235780,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": true
    },
    {
        "id": "infinix-infinix-note-40-8-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Note 40",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 168320,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-note-40-pro-8-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Note 40 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 207860,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-note-40-pro-12-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Note 40 Pro+",
        "variant": "12+256GB",
        "ram": "12GB",
        "storage": "256GB",
        "price": 258760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-zero-40-8-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Zero 40",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 242350,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-zero-40-pro-12-512gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Zero 40 Pro",
        "variant": "12+512GB",
        "ram": "12GB",
        "storage": "512GB",
        "price": 313780,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": true
    },
    {
        "id": "infinix-infinix-hot-50-4-128gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Hot 50",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 114780,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-hot-50i-4-128gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Hot 50i",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 101460,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-hot-50-pro-8-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Hot 50 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 158760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-hot-40-8-128gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Hot 40",
        "variant": "8+128GB",
        "ram": "8GB",
        "storage": "128GB",
        "price": 97650,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-hot-40i-4-128gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Hot 40i",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 83420,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-smart-9-3-64gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Smart 9",
        "variant": "3+64GB",
        "ram": "3GB",
        "storage": "64GB",
        "price": 71680,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-smart-8-3-64gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Smart 8",
        "variant": "3+64GB",
        "ram": "3GB",
        "storage": "64GB",
        "price": 65390,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-smart-8-pro-4-128gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Smart 8 Pro",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 88760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-gt-20-pro-12-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "GT 20 Pro",
        "variant": "12+256GB",
        "ram": "12GB",
        "storage": "256GB",
        "price": 279450,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": true
    },
    {
        "id": "infinix-infinix-gt-10-pro-8-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "GT 10 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 238760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-zero-5g-8-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Zero 5G",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 196780,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-zero-ultra-8-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Zero Ultra",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 281970,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-note-12-6-128gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Note 12",
        "variant": "6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 142690,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-note-12-pro-8-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Note 12 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 166430,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-hot-12-4-128gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Hot 12",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 98760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-hot-12-play-4-64gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Hot 12 Play",
        "variant": "4+64GB",
        "ram": "4GB",
        "storage": "64GB",
        "price": 78620,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-smart-7-2-64gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Smart 7",
        "variant": "2+64GB",
        "ram": "2GB",
        "storage": "64GB",
        "price": 52780,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-smart-7-hd-2-64gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Smart 7 HD",
        "variant": "2+64GB",
        "ram": "2GB",
        "storage": "64GB",
        "price": 48650,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-zero-8-6-128gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Zero 8",
        "variant": "6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 153420,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-zero-8i-6-128gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Zero 8i",
        "variant": "6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 139760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-note-11-4-128gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Note 11",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 110350,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "infinix-infinix-note-11-pro-8-256gb",
        "brand": "Infinix",
        "category": "Smartphones",
        "model": "Note 11 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 149860,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-14c-4-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 14C",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 118760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-14c-6-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 14C",
        "variant": "6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 139680,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-a3-3-64gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi A3",
        "variant": "3+64GB",
        "ram": "3GB",
        "storage": "64GB",
        "price": 86450,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-a3-4-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi A3",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 101230,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-13c-6-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 13C",
        "variant": "6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 121870,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-13c-8-256gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 13C",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 146760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-13-6-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 13",
        "variant": "6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 148560,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-13-8-256gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 13",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 175680,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-note-13-6-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi Note 13",
        "variant": "6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 162430,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-note-13-8-256gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi Note 13",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 192760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-note-13-pro-8-256gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi Note 13 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 248860,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-note-13-pro-12-512gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi Note 13 Pro+",
        "variant": "12+512GB",
        "ram": "12GB",
        "storage": "512GB",
        "price": 342750,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": true
    },
    {
        "id": "xiaomi-redmi-note-12-4-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi Note 12",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 116780,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-note-12-6-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi Note 12",
        "variant": "6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 134760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-note-12-pro-8-256gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi Note 12 Pro",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 187460,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-note-12-pro-8-256gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi Note 12 Pro+",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 213640,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-12-4-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 12",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 109780,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-12-8-256gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 12",
        "variant": "8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 139860,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-12c-3-64gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 12C",
        "variant": "3+64GB",
        "ram": "3GB",
        "storage": "64GB",
        "price": 69840,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-12c-4-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 12C",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 87650,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-10-4-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 10",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 92780,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-10c-4-64gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 10C",
        "variant": "4+64GB",
        "ram": "4GB",
        "storage": "64GB",
        "price": 72460,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-10a-3-64gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 10A",
        "variant": "3+64GB",
        "ram": "3GB",
        "storage": "64GB",
        "price": 58760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-9a-2-32gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 9A",
        "variant": "2+32GB",
        "ram": "2GB",
        "storage": "32GB",
        "price": 49870,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-9c-3-64gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 9C",
        "variant": "3+64GB",
        "ram": "3GB",
        "storage": "64GB",
        "price": 63450,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-9-4-64gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi 9",
        "variant": "4+64GB",
        "ram": "4GB",
        "storage": "64GB",
        "price": 78320,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-note-11-4-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi Note 11",
        "variant": "4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 126450,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "xiaomi-redmi-note-11-pro-6-128gb",
        "brand": "Xiaomi",
        "category": "Smartphones",
        "model": "Redmi Note 11 Pro",
        "variant": "6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 153760,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },

    // Samsung catalogue — appended from supplied catalogue image.
    {
        "id": "samsung-fold-7-16-1tb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "Fold 7",
        "variant": "Fold 7 16+1TB",
        "ram": "16GB",
        "storage": "1TB",
        "price": 3288710,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-fold-7-12-512gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "Fold 7",
        "variant": "Fold 7 12+512GB",
        "ram": "12GB",
        "storage": "512GB",
        "price": 2893550,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-fold-7-12-256gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "Fold 7",
        "variant": "Fold 7 12+256GB",
        "ram": "12GB",
        "storage": "256GB",
        "price": 2707300,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-flip-7-12-512gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "Flip 7",
        "variant": "Flip 7 12+512GB",
        "ram": "12GB",
        "storage": "512GB",
        "price": 1764060,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-flip-7-12-256gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "Flip 7",
        "variant": "Flip 7 12+256GB",
        "ram": "12GB",
        "storage": "256GB",
        "price": 1546600,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-flip-7-fe-8-256gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "Flip 7 FE",
        "variant": "Flip 7 FE 8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 1359020,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-flip-7-fe-8-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "Flip 7 FE",
        "variant": "Flip 7 FE 8+128GB",
        "ram": "8GB",
        "storage": "128GB",
        "price": 1265730,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-s26-ultra-16-512gb-wo-ta",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "S26 Ultra",
        "variant": "S26 Ultra 16+512GB W/o TA",
        "ram": "16GB",
        "storage": "512GB",
        "price": 2219670,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-s26-ultra-12-512gb-wo-ta",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "S26 Ultra",
        "variant": "S26 Ultra 12+512GB W/o TA",
        "ram": "12GB",
        "storage": "512GB",
        "price": 1895500,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-s26-ultra-12-256gb-wo-ta",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "S26 Ultra",
        "variant": "S26 Ultra 12+256GB W/o TA",
        "ram": "12GB",
        "storage": "256GB",
        "price": 1615310,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-s26-plus-12-512gb-wo-ta",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "S26+",
        "variant": "S26+ 12+512GB W/o TA",
        "ram": "12GB",
        "storage": "512GB",
        "price": 1604730,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-s26-plus-12-256gb-wo-ta",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "S26+",
        "variant": "S26+ 12+256GB W/o TA",
        "ram": "12GB",
        "storage": "256GB",
        "price": 1362990,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-s26-12-256gb-wo-ta",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "S26",
        "variant": "S26 12+256GB W/o TA",
        "ram": "12GB",
        "storage": "256GB",
        "price": 1143910,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-s25-fe-8-256gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "S25 FE",
        "variant": "S25 FE 8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 990400,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a57-5g-8-256gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A57 5G",
        "variant": "A57 5G 8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 660790,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a57-5g-8-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A57 5G",
        "variant": "A57 5G 8+128GB",
        "ram": "8GB",
        "storage": "128GB",
        "price": 589610,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a56-5g-8-256gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A56 5G",
        "variant": "A56 5G 8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 625140,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a56-5g-8-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A56 5G",
        "variant": "A56 5G 8+128GB",
        "ram": "8GB",
        "storage": "128GB",
        "price": 584770,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a37-5g-8-256gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A37 5G",
        "variant": "A37 5G 8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 583420,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a37-5g-6-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A37 5G",
        "variant": "A37 5G 6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 476660,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a36-5g-8-256gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A36 5G",
        "variant": "A36 5G 8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 537650,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a36-5g-6-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A36 5G",
        "variant": "A36 5G 6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 461930,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a27-5g-8-256gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A27 5G",
        "variant": "A27 5G 8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 495670,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a27-5g-6-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A27 5G",
        "variant": "A27 5G 6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 391420,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a26-5g-8-256gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A26 5G",
        "variant": "A26 5G 8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 466470,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a26-5g-6-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A26 5G",
        "variant": "A26 5G 6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 367780,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a17-5g-4-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A17 5G",
        "variant": "A17 5G 4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 290794,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a17-lte-8-256gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A17 LTE",
        "variant": "A17 LTE 8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 357382,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a17-lte-6-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A17 LTE",
        "variant": "A17 LTE 6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 271680,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a17-lte-4-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A17 LTE",
        "variant": "A17 LTE 4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 243175,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a16-lte-4-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A16 LTE",
        "variant": "A16 LTE 4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 201390,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a07-4-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A07",
        "variant": "A07 4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 201133,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a07-4-64gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A07",
        "variant": "A07 4+64GB",
        "ram": "4GB",
        "storage": "64GB",
        "price": 172628,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a06-lte-4-128gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A06 LTE",
        "variant": "A06 LTE 4+128GB",
        "ram": "4GB",
        "storage": "128GB",
        "price": 154924,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-a06-lte-4-64gb",
        "brand": "Samsung",
        "category": "Smartphones",
        "model": "A06 LTE",
        "variant": "A06 LTE 4+64GB",
        "ram": "4GB",
        "storage": "64GB",
        "price": 134981,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-s11-ultra-5g-12-512gb-w-kb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab S11 Ultra 5G",
        "variant": "Tab S11 Ultra 5G 12+512GB (W/ KB)",
        "ram": "12GB",
        "storage": "512GB",
        "price": 2223560,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-s11-ultra-5g-12-512gb-wo-kb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab S11 Ultra 5G",
        "variant": "Tab S11 Ultra 5G 12+512GB (W/o KB)",
        "ram": "12GB",
        "storage": "512GB",
        "price": 2065500,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-s11-ultra-5g-12-256gb-w-kb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab S11 Ultra 5G",
        "variant": "Tab S11 Ultra 5G 12+256GB (W/ KB)",
        "ram": "12GB",
        "storage": "256GB",
        "price": 1928290,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-s11-ultra-5g-12-256gb-wo-kb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab S11 Ultra 5G",
        "variant": "Tab S11 Ultra 5G 12+256GB (W/o KB)",
        "ram": "12GB",
        "storage": "256GB",
        "price": 1817840,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-s11-5g-12-512gb-wo-kb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab S11 5G",
        "variant": "Tab S11 5G 12+512GB (W/o KB)",
        "ram": "12GB",
        "storage": "512GB",
        "price": 1694100,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-s11-5g-12-256gb-wo-kb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab S11 5G",
        "variant": "Tab S11 5G 12+256GB (W/o KB)",
        "ram": "12GB",
        "storage": "256GB",
        "price": 1446590,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-s11-5g-12-128gb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab S11 5G",
        "variant": "Tab S11 5G 12+128GB",
        "ram": "12GB",
        "storage": "128GB",
        "price": 1322860,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-s10-fe-plus-5g-8-128gb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab S10 FE+ 5G",
        "variant": "Tab S10 FE+ 5G 8+128GB",
        "ram": "8GB",
        "storage": "128GB",
        "price": 1009870,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-s10-fe-5g-8-128gb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab S10 FE 5G",
        "variant": "Tab S10 FE 5G 8+128GB",
        "ram": "8GB",
        "storage": "128GB",
        "price": 823270,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-a11-plus-5g-8-256gb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab A11+ 5G",
        "variant": "Tab A11+ 5G 8+256GB",
        "ram": "8GB",
        "storage": "256GB",
        "price": 468440,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-a11-plus-5g-6-128gb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab A11+ 5G",
        "variant": "Tab A11+ 5G 6+128GB",
        "ram": "6GB",
        "storage": "128GB",
        "price": 387750,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-a11-lte-8-128gb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab A11 LTE",
        "variant": "Tab A11 LTE 8+128GB",
        "ram": "8GB",
        "storage": "128GB",
        "price": 268000,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    },
    {
        "id": "samsung-tab-a11-lte-4-64gb",
        "brand": "Samsung",
        "category": "Tablets",
        "model": "Tab A11 LTE",
        "variant": "Tab A11 LTE 4+64GB",
        "ram": "4GB",
        "storage": "64GB",
        "price": 198390,
        "currency": "NGN",
        "displayPrice": "",
        "image": "/images/products/samsung/placeholder.svg",
        "availability": "Available",
        "description": "",
        "featured": false
    }
];

window.MULTITALENTED_PRODUCTS = products;
